//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixProUsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Com_Main
    {
        public int Id { get; set; }
        public string TwilioAccountSid { get; set; }
        public string TwilioauthToken { get; set; }
        public string TwilioFromPhoneNumber { get; set; }
        public string RealtyRapidApi { get; set; }
        public string AddressAutoCompleteKey { get; set; }
    }
}
