//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixProUsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Equipments
    {
        public int Id { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> BrancheId { get; set; }
        public string EquipmentName { get; set; }
        public string MakeModel { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public string AssigntoMulti { get; set; }
        public Nullable<int> Assignto { get; set; }
        public Nullable<int> Unite { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> MaintenanceDue { get; set; }
        public Nullable<int> MaintenanceDueTime { get; set; }
        public Nullable<decimal> MaintenanceCost { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Tbl_Customers Tbl_Customers { get; set; }
        public virtual Tbl_Account Tbl_Account { get; set; }
        public virtual Tbl_Branches Tbl_Branches { get; set; }
        public virtual Tbl_Employee Tbl_Employee { get; set; }
        public virtual Tbl_Employee Tbl_Employee1 { get; set; }
    }
}
