//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixProUsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Customers()
        {
            this.Tbl_Calls = new HashSet<Tbl_Calls>();
            this.Tbl_Equipments = new HashSet<Tbl_Equipments>();
            this.Tbl_Estimate = new HashSet<Tbl_Estimate>();
            this.Tbl_Schedule = new HashSet<Tbl_Schedule>();
            this.Tbl_TransactionCustomersCustomField = new HashSet<Tbl_TransactionCustomersCustomField>();
            this.Tbl_ScheduleMaterialReceipt = new HashSet<Tbl_ScheduleMaterialReceipt>();
            this.Tbl_Invoice = new HashSet<Tbl_Invoice>();
            this.Tbl_Payment = new HashSet<Tbl_Payment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> BrancheId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> Since { get; set; }
        public Nullable<int> CustomerType { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> TaxId { get; set; }
        public Nullable<bool> Taxable { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string Country { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalcodeZIP { get; set; }
        public string YearBuit { get; set; }
        public string Squirefootage { get; set; }
        public string YearEstimedValue { get; set; }
        public string EstimedValue { get; set; }
        public string locationlatitude { get; set; }
        public string locationlongitude { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public Nullable<bool> AllowLogin { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Source { get; set; }
        public Nullable<bool> MemeberType { get; set; }
        public Nullable<int> MemeberId { get; set; }
        public Nullable<System.DateTime> MemeberExpireDate { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Calls> Tbl_Calls { get; set; }
        public virtual Tbl_CustomersCategory Tbl_CustomersCategory { get; set; }
        public virtual Tbl_Member Tbl_Member { get; set; }
        public virtual Tbl_Tax Tbl_Tax { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Equipments> Tbl_Equipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Estimate> Tbl_Estimate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Schedule> Tbl_Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TransactionCustomersCustomField> Tbl_TransactionCustomersCustomField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ScheduleMaterialReceipt> Tbl_ScheduleMaterialReceipt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Invoice> Tbl_Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Payment> Tbl_Payment { get; set; }
        public virtual Tbl_Account Tbl_Account { get; set; }
        public virtual Tbl_Branches Tbl_Branches { get; set; }
        public virtual Tbl_Employee Tbl_Employee { get; set; }
    }
}
