//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixProUsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ScheduleMaterialReceipt
    {
        public int Id { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> BrancheId { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public Nullable<int> ScheduleDateId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> TechnicianId { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Notes { get; set; }
        public string ReceiptPhoto { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Tbl_Customers Tbl_Customers { get; set; }
        public virtual Tbl_Schedule Tbl_Schedule { get; set; }
        public virtual Tbl_ScheduleDate Tbl_ScheduleDate { get; set; }
        public virtual Tbl_Account Tbl_Account { get; set; }
        public virtual Tbl_Branches Tbl_Branches { get; set; }
        public virtual Tbl_Employee Tbl_Employee { get; set; }
    }
}
