//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixProUsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ScheduleEmployees
    {
        public int Id { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> ScheduleDateId { get; set; }
        public Nullable<int> EmployeeCategoryId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string SpentTimeHour { get; set; }
        public string SpentTimeMin { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<decimal> Labor { get; set; }
        public Nullable<int> Status { get; set; }
        public string Reasonnotserve { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Tbl_EmployeeCategory Tbl_EmployeeCategory { get; set; }
        public virtual Tbl_ScheduleDate Tbl_ScheduleDate { get; set; }
        public virtual Tbl_Account Tbl_Account { get; set; }
        public virtual Tbl_Employee Tbl_Employee { get; set; }
        public virtual Tbl_Employee Tbl_Employee1 { get; set; }
    }
}
