//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixProUsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ScheduleDate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_ScheduleDate()
        {
            this.Tbl_SchedulePictures = new HashSet<Tbl_SchedulePictures>();
            this.Tbl_ScheduleMaterialReceipt = new HashSet<Tbl_ScheduleMaterialReceipt>();
            this.Tbl_ScheduleItemsServices = new HashSet<Tbl_ScheduleItemsServices>();
            this.Tbl_InvoiceScheduleDate = new HashSet<Tbl_InvoiceScheduleDate>();
            this.Tbl_ScheduleEmployees = new HashSet<Tbl_ScheduleEmployees>();
            this.Tbl_EstimateScheduleDate = new HashSet<Tbl_EstimateScheduleDate>();
            this.Tbl_OneSignalNotification = new HashSet<Tbl_OneSignalNotification>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> BrancheId { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public string Date { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public Nullable<int> Status { get; set; }
        public string CalendarColor { get; set; }
        public string Reasonnotserve { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<int> EstimateId { get; set; }
        public Nullable<int> CreateOrginal_Custom { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Tbl_Estimate Tbl_Estimate { get; set; }
        public virtual Tbl_Schedule Tbl_Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_SchedulePictures> Tbl_SchedulePictures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ScheduleMaterialReceipt> Tbl_ScheduleMaterialReceipt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ScheduleItemsServices> Tbl_ScheduleItemsServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_InvoiceScheduleDate> Tbl_InvoiceScheduleDate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ScheduleEmployees> Tbl_ScheduleEmployees { get; set; }
        public virtual Tbl_Invoice Tbl_Invoice { get; set; }
        public virtual Tbl_Account Tbl_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_EstimateScheduleDate> Tbl_EstimateScheduleDate { get; set; }
        public virtual Tbl_Branches Tbl_Branches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_OneSignalNotification> Tbl_OneSignalNotification { get; set; }
        public virtual Tbl_Employee Tbl_Employee { get; set; }
    }
}
