//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixProUsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Plans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Plans()
        {
            this.Tbl_Account = new HashSet<Tbl_Account>();
            this.Tbl_AccountPayment = new HashSet<Tbl_AccountPayment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string MonthlyPrice { get; set; }
        public string AnnualPrice { get; set; }
        public string CountUsers { get; set; }
        public Nullable<bool> Support { get; set; }
        public Nullable<bool> CustomFields { get; set; }
        public Nullable<bool> UsersNotificationSettings { get; set; }
        public Nullable<bool> ReminderRules { get; set; }
        public Nullable<bool> Branches { get; set; }
        public Nullable<bool> Customers { get; set; }
        public Nullable<bool> UsersPermission { get; set; }
        public Nullable<bool> Equipmets { get; set; }
        public Nullable<bool> TimeSheet { get; set; }
        public Nullable<bool> Scheduling { get; set; }
        public Nullable<bool> Expenses { get; set; }
        public Nullable<bool> InvoiceQuotes { get; set; }
        public Nullable<bool> Contracts { get; set; }
        public Nullable<bool> Payment { get; set; }
        public Nullable<bool> Notes { get; set; }
        public Nullable<bool> MessagesChat { get; set; }
        public Nullable<bool> Tracking { get; set; }
        public Nullable<bool> Map { get; set; }
        public Nullable<bool> Reporting { get; set; }
        public Nullable<bool> CustomersSection { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Account> Tbl_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_AccountPayment> Tbl_AccountPayment { get; set; }
    }
}
