//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixProUsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Calls
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Calls()
        {
            this.Tbl_Schedule1 = new HashSet<Tbl_Schedule>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> BrancheId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public string PhoneNum { get; set; }
        public Nullable<int> ReasonId { get; set; }
        public Nullable<int> CampaignId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Tbl_CallReason Tbl_CallReason { get; set; }
        public virtual Tbl_Campaigns Tbl_Campaigns { get; set; }
        public virtual Tbl_Customers Tbl_Customers { get; set; }
        public virtual Tbl_Schedule Tbl_Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Schedule> Tbl_Schedule1 { get; set; }
        public virtual Tbl_ItemsServices Tbl_ItemsServices { get; set; }
        public virtual Tbl_Account Tbl_Account { get; set; }
        public virtual Tbl_Account Tbl_Account1 { get; set; }
        public virtual Tbl_Branches Tbl_Branches { get; set; }
        public virtual Tbl_Employee Tbl_Employee { get; set; }
    }
}
