//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixProUsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_InvoiceScheduleDate
    {
        public int Id { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<int> ScheduleDateId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Tbl_ScheduleDate Tbl_ScheduleDate { get; set; }
        public virtual Tbl_Invoice Tbl_Invoice { get; set; }
        public virtual Tbl_Account Tbl_Account { get; set; }
        public virtual Tbl_Employee Tbl_Employee { get; set; }
    }
}
