//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixProUsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Estimate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Estimate()
        {
            this.Tbl_EstimateItemsServices = new HashSet<Tbl_EstimateItemsServices>();
            this.Tbl_ScheduleDate = new HashSet<Tbl_ScheduleDate>();
            this.Tbl_Invoice = new HashSet<Tbl_Invoice>();
            this.Tbl_EstimateScheduleDate = new HashSet<Tbl_EstimateScheduleDate>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> BrancheId { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public Nullable<System.DateTime> EstimateDate { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> TaxId { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Taxval { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string DiscountAmountOrPercent { get; set; }
        public Nullable<decimal> Net { get; set; }
        public Nullable<int> Status { get; set; }
        public string SignaturePrintName { get; set; }
        public string SignatureDraw { get; set; }
        public string Terms { get; set; }
        public string NotesForCustomer { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> InvoiceId { get; set; }
    
        public virtual Tbl_Customers Tbl_Customers { get; set; }
        public virtual Tbl_Member Tbl_Member { get; set; }
        public virtual Tbl_Schedule Tbl_Schedule { get; set; }
        public virtual Tbl_Tax Tbl_Tax { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_EstimateItemsServices> Tbl_EstimateItemsServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ScheduleDate> Tbl_ScheduleDate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Invoice> Tbl_Invoice { get; set; }
        public virtual Tbl_Account Tbl_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_EstimateScheduleDate> Tbl_EstimateScheduleDate { get; set; }
        public virtual Tbl_Branches Tbl_Branches { get; set; }
        public virtual Tbl_Employee Tbl_Employee { get; set; }
    }
}
