//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixProUsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Employee()
        {
            this.Tbl_Branches = new HashSet<Tbl_Branches>();
            this.Tbl_CallReason = new HashSet<Tbl_CallReason>();
            this.Tbl_Calls = new HashSet<Tbl_Calls>();
            this.Tbl_Campaigns = new HashSet<Tbl_Campaigns>();
            this.Tbl_Customers = new HashSet<Tbl_Customers>();
            this.Tbl_CustomersCategory = new HashSet<Tbl_CustomersCategory>();
            this.Tbl_CustomersCustomField = new HashSet<Tbl_CustomersCustomField>();
            this.Tbl_EmployeeAssignItemsLogs = new HashSet<Tbl_EmployeeAssignItemsLogs>();
            this.Tbl_EmployeeAssignItems = new HashSet<Tbl_EmployeeAssignItems>();
            this.Tbl_EmployeeAssignItems1 = new HashSet<Tbl_EmployeeAssignItems>();
            this.Tbl_EmployeeAssignItemsLogs1 = new HashSet<Tbl_EmployeeAssignItemsLogs>();
            this.Tbl_EmployeeBranches = new HashSet<Tbl_EmployeeBranches>();
            this.Tbl_EmployeeBranches1 = new HashSet<Tbl_EmployeeBranches>();
            this.Tbl_EmployeeCategory1 = new HashSet<Tbl_EmployeeCategory>();
            this.Tbl_EmployeeCustomField = new HashSet<Tbl_EmployeeCustomField>();
            this.Tbl_Equipments = new HashSet<Tbl_Equipments>();
            this.Tbl_Equipments1 = new HashSet<Tbl_Equipments>();
            this.Tbl_EquipmentsCustomField = new HashSet<Tbl_EquipmentsCustomField>();
            this.Tbl_Estimate = new HashSet<Tbl_Estimate>();
            this.Tbl_EstimateItemsServices = new HashSet<Tbl_EstimateItemsServices>();
            this.Tbl_EstimateScheduleDate = new HashSet<Tbl_EstimateScheduleDate>();
            this.Tbl_Invoice = new HashSet<Tbl_Invoice>();
            this.Tbl_InvoiceItemsServices = new HashSet<Tbl_InvoiceItemsServices>();
            this.Tbl_InvoiceScheduleDate = new HashSet<Tbl_InvoiceScheduleDate>();
            this.Tbl_ItemsServices = new HashSet<Tbl_ItemsServices>();
            this.Tbl_ItemsServicesCategory = new HashSet<Tbl_ItemsServicesCategory>();
            this.Tbl_ItemsServicesSubCategory = new HashSet<Tbl_ItemsServicesSubCategory>();
            this.Tbl_Member = new HashSet<Tbl_Member>();
            this.Tbl_OneSignalNotification = new HashSet<Tbl_OneSignalNotification>();
            this.Tbl_OneSignalNotification1 = new HashSet<Tbl_OneSignalNotification>();
            this.Tbl_Payment = new HashSet<Tbl_Payment>();
            this.Tbl_Schedule = new HashSet<Tbl_Schedule>();
            this.Tbl_ScheduleDate = new HashSet<Tbl_ScheduleDate>();
            this.Tbl_ScheduleEmployees = new HashSet<Tbl_ScheduleEmployees>();
            this.Tbl_ScheduleEmployees1 = new HashSet<Tbl_ScheduleEmployees>();
            this.Tbl_ScheduleItemsServices = new HashSet<Tbl_ScheduleItemsServices>();
            this.Tbl_ScheduleMaterialReceipt = new HashSet<Tbl_ScheduleMaterialReceipt>();
            this.Tbl_SchedulePictures = new HashSet<Tbl_SchedulePictures>();
            this.Tbl_StripeAccount = new HashSet<Tbl_StripeAccount>();
            this.Tbl_Tax = new HashSet<Tbl_Tax>();
            this.Tbl_TimeSheet = new HashSet<Tbl_TimeSheet>();
            this.Tbl_TimeSheet1 = new HashSet<Tbl_TimeSheet>();
            this.Tbl_TransactionCustomersCustomField = new HashSet<Tbl_TransactionCustomersCustomField>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<System.DateTime> Since { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> SalaeryPer { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string UserName { get; set; }
        public string EmailUserName { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalcodeZIP { get; set; }
        public string locationlatitude { get; set; }
        public string locationlongitude { get; set; }
        public string Country { get; set; }
        public string SSN { get; set; }
        public string DriveLicense { get; set; }
        public string Picture { get; set; }
        public Nullable<int> UserRole { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string TheBranchs { get; set; }
        public string Employees { get; set; }
        public Nullable<bool> ActiveHome { get; set; }
        public Nullable<bool> ActiveBranches { get; set; }
        public Nullable<bool> ActiveContract { get; set; }
        public Nullable<bool> ActiveCustomers { get; set; }
        public Nullable<bool> ActiveCustomersCategory { get; set; }
        public Nullable<bool> ActiveCustomersCustomField { get; set; }
        public Nullable<bool> ActiveEmployee { get; set; }
        public Nullable<bool> ActiveEmployeeCategory { get; set; }
        public Nullable<bool> ActiveEmployeeCustomField { get; set; }
        public Nullable<bool> ActiveEstimate { get; set; }
        public Nullable<bool> ActiveEstimateEmailTemplate { get; set; }
        public Nullable<bool> ActiveExpenses { get; set; }
        public Nullable<bool> ActiveExpensesCategory { get; set; }
        public Nullable<bool> ActiveEquipments { get; set; }
        public Nullable<bool> ActiveEquipmentsCustomField { get; set; }
        public Nullable<bool> ActiveItemsServices { get; set; }
        public Nullable<bool> ActiveItemsServicesCategory { get; set; }
        public Nullable<bool> ActiveItemsServicesCustomField { get; set; }
        public Nullable<bool> ActiveMember { get; set; }
        public Nullable<bool> ActiveTimeSheet { get; set; }
        public Nullable<bool> ActiveInvoice { get; set; }
        public Nullable<bool> ActiveInvoiceEmailTemplate { get; set; }
        public Nullable<bool> ActiveMap { get; set; }
        public Nullable<bool> ActiveNotes { get; set; }
        public Nullable<bool> ActiveNotificationSettings { get; set; }
        public Nullable<bool> ActivePayment { get; set; }
        public Nullable<bool> ActiveReminderRules { get; set; }
        public Nullable<bool> ActiveRoute { get; set; }
        public Nullable<bool> ActiveSchedule { get; set; }
        public Nullable<bool> ActiveSettings { get; set; }
        public Nullable<bool> ActiveTax { get; set; }
        public Nullable<bool> ActiveReport { get; set; }
        public Nullable<bool> ActiveStripeAccount { get; set; }
        public Nullable<bool> ActiveMessage { get; set; }
        public Nullable<bool> ActiveItemsServicesSubCategory { get; set; }
        public Nullable<bool> ActiveAccount { get; set; }
        public Nullable<bool> ActiveCalls { get; set; }
        public Nullable<bool> ActiveCampaigns { get; set; }
        public Nullable<bool> ActiveCallReason { get; set; }
        public Nullable<bool> ActiveAllScdTr_FaorTrOnly { get; set; }
        public Nullable<bool> ActiveEditCustomer { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> ActiveEditPrice { get; set; }
        public Nullable<bool> ActiveEditEstimate_Invoice { get; set; }
        public Nullable<bool> ActiveMobileLogin { get; set; }
        public Nullable<bool> ActiveMobileTrackStaff { get; set; }
        public Nullable<bool> ActiveCreateSchedule { get; set; }
        public string OneSignalPlayerId { get; set; }
        public string UserIdMysql { get; set; }
        public Nullable<bool> ActiveCustomerPhone { get; set; }
    
        public virtual Tbl_Account Tbl_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Branches> Tbl_Branches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_CallReason> Tbl_CallReason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Calls> Tbl_Calls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Campaigns> Tbl_Campaigns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Customers> Tbl_Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_CustomersCategory> Tbl_CustomersCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_CustomersCustomField> Tbl_CustomersCustomField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_EmployeeAssignItemsLogs> Tbl_EmployeeAssignItemsLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_EmployeeAssignItems> Tbl_EmployeeAssignItems { get; set; }
        public virtual Tbl_EmployeeCategory Tbl_EmployeeCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_EmployeeAssignItems> Tbl_EmployeeAssignItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_EmployeeAssignItemsLogs> Tbl_EmployeeAssignItemsLogs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_EmployeeBranches> Tbl_EmployeeBranches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_EmployeeBranches> Tbl_EmployeeBranches1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_EmployeeCategory> Tbl_EmployeeCategory1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_EmployeeCustomField> Tbl_EmployeeCustomField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Equipments> Tbl_Equipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Equipments> Tbl_Equipments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_EquipmentsCustomField> Tbl_EquipmentsCustomField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Estimate> Tbl_Estimate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_EstimateItemsServices> Tbl_EstimateItemsServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_EstimateScheduleDate> Tbl_EstimateScheduleDate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Invoice> Tbl_Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_InvoiceItemsServices> Tbl_InvoiceItemsServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_InvoiceScheduleDate> Tbl_InvoiceScheduleDate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ItemsServices> Tbl_ItemsServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ItemsServicesCategory> Tbl_ItemsServicesCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ItemsServicesSubCategory> Tbl_ItemsServicesSubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Member> Tbl_Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_OneSignalNotification> Tbl_OneSignalNotification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_OneSignalNotification> Tbl_OneSignalNotification1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Payment> Tbl_Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Schedule> Tbl_Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ScheduleDate> Tbl_ScheduleDate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ScheduleEmployees> Tbl_ScheduleEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ScheduleEmployees> Tbl_ScheduleEmployees1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ScheduleItemsServices> Tbl_ScheduleItemsServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ScheduleMaterialReceipt> Tbl_ScheduleMaterialReceipt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_SchedulePictures> Tbl_SchedulePictures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_StripeAccount> Tbl_StripeAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Tax> Tbl_Tax { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TimeSheet> Tbl_TimeSheet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TimeSheet> Tbl_TimeSheet1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_TransactionCustomersCustomField> Tbl_TransactionCustomersCustomField { get; set; }
    }
}
